// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN9-ynZJwxfsFyLAxmW3E1ufF0MVq0A3Y',
    appId: '1:665554379758:web:0c034577d02f59ac6ea4ff',
    messagingSenderId: '665554379758',
    projectId: 'cuocthi-khdl',
    authDomain: 'cuocthi-khdl.firebaseapp.com',
    storageBucket: 'cuocthi-khdl.firebasestorage.app',
    measurementId: 'G-4E97GPK84K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJTAMBEStczmZiYtfvFtKeqYNf3DPv6jQ',
    appId: '1:665554379758:android:9fca21cb44ac285f6ea4ff',
    messagingSenderId: '665554379758',
    projectId: 'cuocthi-khdl',
    storageBucket: 'cuocthi-khdl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcVhvLfzc8Cwn_pu-oX0az7g0gWqYnw4g',
    appId: '1:665554379758:ios:749594f141e85a956ea4ff',
    messagingSenderId: '665554379758',
    projectId: 'cuocthi-khdl',
    storageBucket: 'cuocthi-khdl.firebasestorage.app',
    iosBundleId: 'com.example.khoahocdulieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcVhvLfzc8Cwn_pu-oX0az7g0gWqYnw4g',
    appId: '1:665554379758:ios:749594f141e85a956ea4ff',
    messagingSenderId: '665554379758',
    projectId: 'cuocthi-khdl',
    storageBucket: 'cuocthi-khdl.firebasestorage.app',
    iosBundleId: 'com.example.khoahocdulieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN9-ynZJwxfsFyLAxmW3E1ufF0MVq0A3Y',
    appId: '1:665554379758:web:c7d8f891f711704f6ea4ff',
    messagingSenderId: '665554379758',
    projectId: 'cuocthi-khdl',
    authDomain: 'cuocthi-khdl.firebaseapp.com',
    storageBucket: 'cuocthi-khdl.firebasestorage.app',
    measurementId: 'G-TB9V3YW5L1',
  );
}
